wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711728775.881845
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      - 71
      - 100
      3:
      - 23
      4: 3.11.8
      5: 0.16.0
      6: 4.35.2
      8:
      - 3
      - 5
      13: windows-amd64
